/**
 * tests/f1-selector-stability.ts — F1 (identity / selector stability) test.
 *
 * Prove: the selectors that describePage generates for a page resolve again
 * after a reload. Then navigate to a different article and check that the
 * same semantic selectors (article, nav, aside, main) still resolve.
 *
 * describePage builds a candidate inventory with stable structural selectors.
 * F1 is identity: the same concept on the same page resolves to the same
 * element. We test this by:
 *   1. Calling describePage, capturing every region's selector.
 *   2. Reloading, calling describePage again.
 *   3. For each original selector: does it still resolve? Is it re-generated?
 *   4. Navigating to a different article and checking semantic tag selectors.
 *
 * Run:  node --experimental-strip-types --env-file=.env tests/f1-selector-stability.ts
 */

import { createContext, sendToolCall } from './foundation-helpers.ts';

const WIKI_CSS = 'https://en.wikipedia.org/wiki/CSS';
const WIKI_HTML = 'https://en.wikipedia.org/wiki/HTML';

interface Region { id: string; role: string; selector?: string; targetable: boolean; }

async function getDescribePageResult(context: any, page: any): Promise<Region[]> {
  const res = await sendToolCall(context, page, 'describePage', {});
  if (!res?.ok) throw new Error(`describePage failed: ${JSON.stringify(res)}`);
  return (res.result?.regions ?? []) as Region[];
}

async function main() {
  console.log('═══ F1 — selector stability across reload and navigation ═══\n');

  const context = await createContext('f1-selector-stability');
  try {
    const page = await context.newPage();

    // ── Phase 1: describePage on Wikipedia /wiki/CSS ──
    console.log('─── PHASE 1: describePage on /wiki/CSS ───');
    await page.goto(WIKI_CSS, { waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(2500);
    const regions1 = await getDescribePageResult(context, page);
    const targetable1 = regions1.filter((r) => r.targetable && r.selector);
    console.log(`  regions: ${regions1.length}, targetable with selector: ${targetable1.length}`);
    for (const r of targetable1.slice(0, 10)) {
      console.log(`    ${r.id}: role=${r.role} sel=${r.selector}`);
    }
    if (targetable1.length > 10) console.log(`    ... and ${targetable1.length - 10} more`);

    // ── Phase 2: reload, describePage again ──
    console.log('\n─── PHASE 2: reload, describePage again ───');
    await page.reload({ waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(2000);
    const regions2 = await getDescribePageResult(context, page);
    const targetable2 = regions2.filter((r) => r.targetable && r.selector);
    console.log(`  regions: ${regions2.length}, targetable with selector: ${targetable2.length}`);

    // For each original selector, check if it still resolves on the page.
    const selectors1 = targetable1.map((r) => r.selector!);
    const resolutionCheck = await page.evaluate((sels: string[]) => {
      return sels.map((s) => {
        try {
          const el = document.querySelector(s);
          return { selector: s, resolves: el !== null, count: el ? 1 : 0 };
        } catch {
          return { selector: s, resolves: false, count: 0, error: true };
        }
      });
    }, selectors1);

    // Also check if the same selectors are re-generated by describePage.
    const selectors2Set = new Set(targetable2.map((r) => r.selector!));
    let stableCount = 0;
    let changedCount = 0;
    const changed: { selector: string; resolves: boolean; regenerated: boolean }[] = [];
    for (const check of resolutionCheck) {
      const regenerated = selectors2Set.has(check.selector);
      if (check.resolves) stableCount++; else changedCount++;
      if (!check.resolves || !regenerated) {
        changed.push({ selector: check.selector, resolves: check.resolves, regenerated });
      }
    }

    console.log(`\n─── PHASE 2 RESULTS: selector stability after reload ───`);
    console.log(`  total selectors (phase 1): ${selectors1.length}`);
    console.log(`  still resolve on page:     ${stableCount} (${stableCount === selectors1.length ? '100% ✓' : `${Math.round(stableCount / selectors1.length * 100)}%`})`);
    console.log(`  failed to resolve:         ${changedCount}`);
    console.log(`  regenerated by describePage: ${[...selectors2Set].filter((s) => selectors1.includes(s)).length} of ${selectors1.length}`);
    if (changed.length > 0) {
      console.log(`  changed selectors:`);
      for (const c of changed.slice(0, 10)) {
        console.log(`    "${c.selector}" — resolves=${c.resolves}, regenerated=${c.regenerated}`);
      }
      if (changed.length > 10) console.log(`    ... and ${changed.length - 10} more`);
    }

    // ── Phase 3: navigate to a different article (SPA-like check) ──
    console.log('\n─── PHASE 3: navigate to /wiki/HTML, check semantic selectors ───');
    await page.goto(WIKI_HTML, { waitUntil: 'domcontentloaded' });
    await page.waitForTimeout(2500);
    const semanticCheck = await page.evaluate(() => {
      const tags = ['article', 'nav', 'aside', 'main', 'header', 'footer', 'section'];
      return tags.map((t) => ({
        tag: t,
        count: document.querySelectorAll(t).length,
        resolves: document.querySelector(t) !== null,
      }));
    });
    for (const c of semanticCheck) {
      console.log(`  ${c.tag}: ${c.resolves ? 'YES' : 'NO'} (${c.count} match(es))`);
    }

    // Also check if the original selectors resolve on the new article (cross-page).
    const crossPageCheck = await page.evaluate((sels: string[]) => {
      return sels.map((s) => {
        try { return { selector: s, resolves: document.querySelector(s) !== null }; }
        catch { return { selector: s, resolves: false }; }
      });
    }, selectors1);
    const crossPageStable = crossPageCheck.filter((c) => c.resolves).length;
    console.log(`\n  original selectors that resolve on /wiki/HTML: ${crossPageStable}/${selectors1.length}`);
    console.log(`  (expected: low — different article has different structure)`);
    console.log(`  (semantic tags are the stable identity, not structural selectors)`);

    // Summary.
    console.log('\n═══ F1 SUMMARY ═══');
    const reloadStable = stableCount === selectors1.length;
    const semanticStable = semanticCheck.filter((c) => c.resolves).length >= 3;
    console.log(`  Reload stability:  ${reloadStable ? 'PROVEN ✓' : 'PARTIAL'} — ${stableCount}/${selectors1.length} selectors survived reload`);
    console.log(`  Semantic stability: ${semanticStable ? 'PROVEN ✓' : 'NOT PROVEN ✗'} — ${semanticCheck.filter((c) => c.resolves).length}/${semanticCheck.length} semantic tags resolve on new article`);
    console.log(`  F1 RESULT: ${reloadStable ? 'PROVEN — selectors are stable identity for the same page' : 'NOT PROVEN — some selectors changed after reload'}`);
  } catch (err) {
    console.error(`ERROR: ${(err as Error).message}`);
    console.error(err);
  } finally {
    try { await context.close(); } catch { /* ignore */ }
  }
}

main().catch((err) => { console.error(err); process.exit(1); });
